#General
tag: 'CPU'
data_workers: 4
eval_every: 1
on_cluster: False
#Run
test: True
train: False
load_model: "/cluster/scratch/mezhang/Experiments/experiment-Tue_Feb_10_06h52m31s/checkpoints/iter-0/checkpoint-20000"
#data
amount_per_it: 10
amount_of_data: 10
full_data: False
#Model
model_name: "microsoft/deberta-v3-base"
#learning args
train_val_ratio: 0.95
lr: 0.00003
n_epochs: 2
weight_decay: 0.
bs_train: 2
bs_eval: 64
fp16: False
epsilon: 0.2
alpha: 0.5
beta: 1.0