#General
tag: 'GPU'
data_workers: 16
eval_every: 2000
on_cluster: True
#Run
test: True
load_model: None
train: True
#data
amount_per_it: 1250000
amount_of_data: 2500000
#Model
model_name: "microsoft/deberta-v3-base"
full_data: True
#learning args
train_val_ratio: 0.98
lr: 0.00002
n_epochs: 1
weight_decay: 0.
bs_train: 16
bs_eval: 16
fp16: False
epsilon: 0.01
alpha: 0.1
beta: 0.5