#General
tag: 'CPU'
data_workers: 4
eval_every: 1
on_cluster: False
#Run
test: True
train: True
load_model: "/cluster/scratch/mezhang/Experiments/experiment-Fri_Feb__6_16h39m25s/checkpoints/iter-1/checkpoint-100000"
#data
amount_per_it: 10
amount_of_data: 10
full_data: False
#Model
model_name: "microsoft/deberta-v3-base"
#learning args
train_val_ratio: 0.95
lr: 0.00003
n_epochs: 2
weight_decay: 0.
bs_train: 2
bs_eval: 64
fp16: False
epsilon: 0.2
alpha: 0.5
beta: 1.0